const csvReader = require('fast-csv')
const xmlConverter = require('xml-js')
const chalk = require('chalk')
const path = require('path')
const fs = require('fs')
const { isArray } = require('lodash')

/**
 * @method discoverExtension
 * @param  {String} fileName - Name of the file
 * @return {String}
 */

const discoverExtension = (fileName) => {
  const extension = path.extname(fileName)

  if (extension !== '') {
    return extension.replace('.', '')
  }

  return ''
}

/**
 * @method sendContent
 * @param  {Object} api - A api object
 * @param  {Object} contents - Object with the content
 * @return {Promise}
 */
const sendContent = async (api, contents) => {
  for (const story of contents) {
    try {
      console.log(
        `${chalk.blue('-')} Creating the story ${story.name}(${story.slug})`
      )
      await api.post('stories', { story })

      console.log(
        `${chalk.green('✓')} ${story.name}(${story.slug}) has been created`
      )
    } catch (e) {
      console.log(
        `${chalk.red('X')} An error ocurred when creating the story ${story.name}(${story.slug}): ${e.message}`
      )
    }

    console.log('')
  }
}

// This function is used to sanitize the json generated by the xml2js() function,
// because with each text generated in the conversion it is encapsulated within
// an object { "_text": 'text'}

const removeJsonTextAttribute = (value, parentElement) => {
  const keyNo = Object.keys(parentElement._parent).length
  const keyName = Object.keys(parentElement._parent)[keyNo - 1]
  parentElement._parent[keyName] = !isNaN(value) ? Number(value) : value
}

/**
 * @method csvParser
 * @param  {String} data - CSV content
 * @param  {String} typeOfContent - Content type
 * @param  {Number} folderID - Storyblok folder id, default value is 0
 * @param  {String} delimiter - Csv file delimiter, default value is ';'
 * @return {Promise}
 */

const csvParser = (data, typeOfContent, folderID = 0, delimiter = ';') => {
  return new Promise((resolve, reject) => {
    console.log()
    console.log(`${chalk.blue('-')} Reading CSV file... `)
    console.log()

    const story = []

    csvReader.parseString(data, { headers: true, delimiter: delimiter })
      .on('error', error => reject(error))
      .on('data', line => {
        const content = Object.keys(line).reduce((acc, key) => {
          acc[key] = line[key]
          return acc
        }, {})

        if (content.path) {
          delete content.path
        }

        story.push({
          slug: line.path || '',
          name: line.title || '',
          parent_id: folderID,
          content: {
            component: typeOfContent,
            ...content
          }
        })
      })
      .on('end', () => {
        resolve(story)
      })
  })
}

const xmlFactoryOfStories = (line, typeOfContent, folderID) => {
  const content = Object.keys(line).reduce((acc, key) => {
    acc[key] = line[key]
    return acc
  }, {})

  if (content.path) {
    delete content.path
  }

  return {
    slug: line.path || '',
    name: line.title || '',
    parent_id: folderID,
    content: {
      component: typeOfContent,
      ...content
    }
  }
}

/**
 * @method xmlParser
 * @param  {Object} data - XML content
 * @param  {String} typeOfContent - Content type
 * @param  {Number} folderID - Storyblok folder id, default value is 0
 * @return {Promise}
 */

const xmlParser = async (data, typeOfContent, folderID = 0) => {
  return new Promise((resolve, reject) => {
    console.log()
    console.log(`${chalk.blue('-')} Reading XML file... `)
    console.log()

    try {
      const options = {
        compact: true,
        trim: true,
        ignoreDoctype: true,
        textFn: removeJsonTextAttribute
      }
      const contentParsed = xmlConverter.xml2js(data, options)

      if (isArray(contentParsed.root.row)) {
        const story = contentParsed.root.row.map(line => xmlFactoryOfStories(line, typeOfContent, folderID))
        return resolve(story)
      }
      const story = xmlFactoryOfStories(contentParsed.root.row, typeOfContent, folderID)
      return resolve([story])
    } catch (error) {
      return reject(error)
    }
  })
}

/**
 * @method jsonParser
 * @param  {Object} data - Json with content
 * @param  {String} typeOfContent - Content type
 * @param  {Number} folderID - Storyblok folder id, default value is 0
 * @return {Promise}
 */

const jsonParser = async (data, typeOfContent, folderID = 0) => {
  console.log()
  console.log(`${chalk.blue('-')} Reading JSON file... `)
  console.log()

  const copyData = JSON.parse(data)
  const story = []

  for (const key of copyData) {
    const { path, title, ...rest } = key
    story.push({
      slug: path || '',
      name: title || '',
      parent_id: folderID,
      content: {
        component: typeOfContent,
        ...rest
      }
    })
  }
  return Promise.resolve(story)
}

/**
 * @typedef {Object} ConvertFileOptions
 * @property {string} type Type of content
 * @property {string} folder Folder ID
 * @property {string} delimiter Delimiter (For csv files)
 *
 * @method convertFile
 * @param  {string} file                path to file
 * @param  {string} extension           file extension
 * @param  {ConvertFileOptions} options options to parser functions
 */
const convertFile = (file, extension, options) => {
  const {
    type,
    folder,
    delimiter
  } = options

  if (extension === 'csv') {
    const dataFromFile = fs.readFileSync(file)
    return csvParser(dataFromFile, type, folder, delimiter)
  }
  if (extension === 'xml') {
    const dataFromFile = fs.readFileSync(file)
    return xmlParser(dataFromFile, type, folder)
  }
  if (extension === 'json') {
    const dataFromFile = fs.readFileSync(file, 'utf-8')
    return jsonParser(dataFromFile, type, folder)
  }

  return Promise.reject(new Error('This file extension is not supported. Please use .xml, .json or .csv'))
}

module.exports = {
  csvParser,
  xmlParser,
  jsonParser,
  sendContent,
  convertFile,
  discoverExtension
}
