const fs = require('fs')

module.exports = function (api, name, space) {
  if (space) {
    if (!api.accessToken) {
      return Promise.reject(new Error('The user is not logged'))
    }

    api.setSpaceId(space)

    return api.post('components', {
      component: {
        name
      }
    })
  }

  var liquid = './views/components/_' + name + '.liquid'
  console.log('Writing template file to ' + liquid)
  fs.writeFileSync(liquid, require('./templates/teaser'))

  var scss = './source/scss/components/below/_' + name + '.scss'
  console.log('Writing scss file to ' + scss)
  fs.writeFileSync(scss, '// Generated by the Storyblok cli')

  console.log()

  return Promise.resolve(true)
}
